#!/bin/bash
# Starts a GDB session on Dota, injects cheat if it is not already present.
# Send SIGINT to Dota with: "kill -2 "$(pidof dota2)"".

dota_pid=$(pidof dota2)
if [ -z "$dota_pid" ]; then
    /bin/echo -e "\\e[31mDota needs to be open before you can inject...\\e[0m"
    exit 1
fi

# pBypass for crash dumps being sent
# You may also want to consider using -nobreakpad in your launch options.
sudo rm -rf /tmp/dumps # Remove if it exists
sudo mkdir /tmp/dumps # Make it as root
sudo chmod 000 /tmp/dumps # No permissions

filename="libMcDota.so"

# https://www.kernel.org/doc/Documentation/security/Yama.txt
sudo echo "2" | sudo tee /proc/sys/kernel/yama/ptrace_scope # Only allows root to inject code. This is temporary until reboot.

# Adjust the Sleep time below for your system if needed. 
# This sends 2 interrupts to CS:GO after gdb attachs so gdb will drop into a shell.
sleep 3 && kill -2 "$dota_pid" && sleep 1 && kill -2 "$dota_pid" &

# dlopen method Credits: Aixxe @ aixxe.net
if grep -q "$filename" /proc/"$dota_pid"/maps; then
    (sudo echo -e "continue\\n"; cat) | sudo gdb -p "$dota_pid"
else
	path="$(pwd)/$filename"
    echo "Injecting build $path"
    (sudo echo -e "set confirm off\\nset \$dlopen = (void*(*)(char*, int)) dlopen\\ncall \$dlopen(\"$path\", 1)\\n"; cat) | sudo gdb -p "$dota_pid"
fi
