#!/bin/bash

dota_pid=$(pidof dota2)
if [ -z "$dota_pid" ]; then
    /bin/echo -e "\\e[31mDota2 needs to be open before you can inject...\\e[0m"
    exit 1
fi

# pBypass for crash dumps being sent
# You may also want to consider using -nobreakpad in your launch options.
sudo rm -rf /tmp/dumps # Remove if it exists
sudo mkdir /tmp/dumps # Make it as root
sudo chmod 000 /tmp/dumps # No permissions

filename="libMcDota.so"

# Credit: Aixxe @ aixxe.net
if grep -q "$filename" /proc/"$dota_pid"/maps; then
    /bin/echo -e "\\e[33mMcDota is already injected... Aborting...\\e[0m"
    exit
fi
echo "Injecting Build ID: $filename"

# https://www.kernel.org/doc/Documentation/security/Yama.txt
sudo echo "2" | sudo tee /proc/sys/kernel/yama/ptrace_scope # Only allows root to ptrace. This is temporary until reboot.

sudo killall -19 steam
sudo killall -19 steamwebhelper

input="$(
sudo gdb -n -q -batch-silent \
  -ex "set logging on" \
  -ex "set logging file /dev/null" \
  -ex "set logging redirect on" \
  -ex "attach $dota_pid" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"$(pwd)/$filename\", 1)" \
  -ex "detach" \
  -ex "quit"
)"

last_line="${input##*$'\n'}"

sleep 0.2
sudo killall -18 steamwebhelper
sudo killall -18 steam

if [ "$last_line" != "\$1 = (void *) 0x0" ]; then
    /bin/echo -e "\\e[32mSuccessfully injected!\\e[0m"
else
    /bin/echo -e "\\e[31mInjection failed, make sure you have compiled...\\e[0m"
fi
